# Generated by Django 5.1.1 on 2024-09-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Reservacion_Horas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposUsuarios',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('no_carnet', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField()),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.tiposusuarios')),
            ],
        ),
    ]
