# Generated by Django 5.1.1 on 2024-10-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Reservacion_Horas', '0002_tiposusuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='tiposusuarios',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='identificador',
        ),
        migrations.AddField(
            model_name='tiposusuarios',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aulaslaboratorios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
        migrations.AlterField(
            model_name='edificios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
        migrations.AlterField(
            model_name='tiposaulas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
        migrations.AlterField(
            model_name='tiposusuarios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado'),
        ),
    ]
