# Generated by Django 5.1.1 on 2024-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Reservacion_Horas', '0003_estado_remove_tiposusuarios_identificador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposusuarios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='tiposusuarios',
            name='identificador',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificador',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
