# Generated by Django 5.1.1 on 2024-10-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Reservacion_Horas', '0004_remove_tiposusuarios_id_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.usuario')),
                ('tanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.tanda')),
            ],
        ),
    ]
