# Generated by Django 5.1.1 on 2024-10-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Reservacion_Horas', '0005_tanda_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoReservacionHoras',
            fields=[
                ('no_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField()),
                ('cantidad_horas', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.aulaslaboratorios')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.empleado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Reservacion_Horas.usuario')),
            ],
        ),
    ]
