# Generated by Django 5.1.1 on 2024-09-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.campus')),
            ],
        ),
        migrations.CreateModel(
            name='AulasLaboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('cupos_reservados', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.edificios')),
                ('tipo_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.tiposaulas')),
            ],
        ),
    ]
